Mute function added
fiendish/aardwolfclientpackage pull request #306
Opened 2022-06-29 15:43 UTC by AardCrowley

Feel free to clean up any code as necessary, or leave as-is.

2022-06-29 17:38 UTC, AardCrowley commented
Had to add a conditional to chat echo due to the replay buffer.

2022-06-29 17:43 UTC, AardCrowley commented
Moved a conditional for isMuted. It should have occurred before the edit mode check, not on the same line.

2022-07-01 15:03 UTC, fiendish requested changes
the aliases and storage need to either be in the echo plugin or in some other plugin because it's possible to have multiple window plugins active simultaneouly

2022-07-01 15:03 UTC, fiendish commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +></trigger>
Why?

2022-07-01 15:03 UTC, fiendish commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +	if playerName:upper() == "CLEAR" then
The indentation is chaotic. Can you clean it up to 3 spaces?

2022-07-01 15:03 UTC, fiendish commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +	EnableTrigger("ignoreStart", false)
btw, ignoreStart can disable itself.

2022-07-01 15:03 UTC, fiendish commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +end
This doesn't appear to be used.

2022-07-01 15:45 UTC, AardCrowley commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +></trigger>
If someone tries to ignore a person, it seems obvious to me that they do not want to hear from them, so it'll automatically attempt to silence the person instead.

2022-07-01 15:45 UTC, AardCrowley commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +	EnableTrigger("ignoreStart", false)
Moved the disable to ignoreStart.

2022-07-01 15:46 UTC, AardCrowley commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +end
Removed this function. I forget why I even bothered with it, but I think it was a bit more involved before in testing phases.

2022-07-01 16:48 UTC, AardCrowley commented on MUSHclient/worlds/plugins/aard_channels_fiendish.xml
> +	if playerName:upper() == "CLEAR" then
Cleaned up the indentation.

2022-07-04 16:17 UTC, fiendish commented on MUSHclient/worlds/plugins/aard_chat_echo.xml
> +         local res, isMuted = CallPlugin("b555825a4a5700c35fa80780", "checkIfMuted", player)
???

2022-07-05 11:38 UTC, AardCrowley commented on MUSHclient/worlds/plugins/aard_chat_echo.xml
> +         local res, isMuted = CallPlugin("b555825a4a5700c35fa80780", "checkIfMuted", player)
Such a silly mistake to miss.

2022-08-07 15:49 UTC, AardCrowley commented
Is there anything else that I need to take care of before this is pulled over? I think I've addressed all the other issues.

2022-08-15 15:42 UTC, AardCrowley commented
Updated Soundpack to include Epics channel per Tymme's request. It currently uses the 'death.wav' sound, but if someone wants to find an 'epics' wav, they can add that to the sounds directory.

2022-08-15 21:17 UTC, fiendish commented
bless. sorry it's taking so long.

2022-08-16 02:49 UTC, AardCrowley commented
> bless. sorry it's taking so long.

No worries! Busy lives, real life, and bug testing all play a part. I know you'll get around to it when you can get around to it. It's no rush - I have it on my end, and I'm not missing out on any updates otherwise.

2022-10-09 08:27 UTC, fiendish commented
Please try https://github.com/fiendish/aardwolfclientpackage/tree/development

2022-10-09 08:27 UTC, closed without merging